### ISSUE TITLE
Showing nothing for few javacript syntax

### ISSUE THREAD

**Issue by Nikhil-7** [ionutvmi/spacegray-vscode#1]
Hi, I am using your theme and really it's nice :+1: 
but I faced a strange issue. It's showing nothing for few twig syntax like if <%%> underscore.js
I am using file 
- html.twig
- issue in underscore.js template  

![first-image](http://i.prntscr.com/ab286889a8ca450b84e5b8626962bd19.png)

![another-image](http://i.prntscr.com/d9a40d894f254e7a9d7048d7ebc1c68f.png)

you can see, if I don't click on this line then I am unable to see this text. 

I really like this theme but don't want to change because of this issue :smile:

**Comment by ionutvmi** [comment]
Can you tell me what language are you using (should be displayed in the lower right area) ?
Can you also paste a snippet of the code that reproduces the issue ?

**Comment by ionutvmi** [comment]
This should be fixed in 1.1.2

Please confirm and I will close this issue.

**Comment by Nikhil-7** [comment]
I am using 
- PHP Symfony framework for this and 
- file was in Twig format
- Issue was in underscore.js template <% if %> condition.

Snippet - 
`<script type="text/template" id="selected-article">
    <input type="checkbox" <% if(disabled == false){ %>id="checkbox<%= id %>" value="<%= id %>" <%= checked %> <% }else{ %> disabled <% } %> class="selectedArticle i-check" >
    <label class="text-info" <% if(disabled == false){ %>for="checkbox<%= id %>"<% } %>><%- name %></label>
</script>`

`
<script type="text/template" id="left-side-ul">
    <% if(id){ %>
        <input type="checkbox" value="<%- id %>" id="cat-<%- id %>" class="i-check category-add-article" <%- checked %>> 
    <% }else{ %>
        <i class="fa fa-book text-primary"></i>
    <% } %>
</script>`

**Comment by ionutvmi** [comment]
Can you please update to the latest version and check if you can see the text ?

**Comment by Nikhil-7** [comment]
Thank you very much, It's working now :) :+1:
