### ISSUE TITLE
Syntax color

### ISSUE THREAD

**Issue by marcelombc** [ionutvmi/spacegray-vscode#2]
The syntax color do not match with the README images.
This is my current syntax color using the Spacegray Ocean Dark:

![screen shot 2016-11-23 at 18 03 26](https://cloud.githubusercontent.com/assets/1358796/20571400/94954e46-b1a7-11e6-8b86-d7b1ba22851e.png)

**Comment by cogoo** [comment]
:( same issue

**Comment by ionutvmi** [comment]
The issue should be fixed in 1.1.4
Please check and reopen this issue if it's not fixed.

**Comment by lutzroeder** [comment]
Same is happening for me in 1.2.0

See #4
