### ISSUE TITLE
File explorer/title theme

### ISSUE THREAD

**Issue by mxstbr** [ionutvmi/spacegray-vscode#3]
Right now when I select the Ocean Dark theme (which I love) this is what I see:

![screen shot 2016-12-19 at 11 59 27](https://cloud.githubusercontent.com/assets/7525670/21310430/9ebabd9e-c5e2-11e6-8509-f69459dfd23d.png)

The file explorer and title colors kill me. It would be awesome if they had the same color scheme as the editor!

For reference, this is what my Atom setup looks like:

![screen shot 2016-12-19 at 12 00 47](https://cloud.githubusercontent.com/assets/7525670/21310470/cb01e292-c5e2-11e6-8fa9-ac37c611517e.png)

Notice the file explorer colors.

**Comment by ionutvmi** [comment]
I'm not sure if we can change those colors at the moment in vscode.

Please see: https://github.com/Microsoft/vscode/issues/3112

I will keep this open until we will have a way to fix it.

**Comment by aaronjheng** [comment]
@ionutvmi [workbench theming](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_11.md#preview-workbench-theming) :)

**Comment by mxstbr** [comment]
Yess, I can't wait!!

![Exciteddddd](https://media.giphy.com/media/yDWCutu4QZ44w/giphy.gif)

**Comment by ionutvmi** [comment]
The changes should be available in v1.2.0

Please let me know if it looks ok on your side.

**Comment by mxstbr** [comment]
It is gorgeous. Thank you so much! 😍 

![screen shot 2017-04-16 at 10 41 46](https://cloud.githubusercontent.com/assets/7525670/25069987/4e925852-2291-11e7-8aee-9f31e42d6b3a.png)
