### ISSUE TITLE
Base 16 Ocean Dark does not match README.me

### ISSUE THREAD

**Issue by lutzroeder** [ionutvmi/spacegray-vscode#4]
Running VSCode Version 1.12.1 (1.12.1)
Installed "Spacegray VSCode 1.2.0"

applied the "Base 16 Ocean Dark" theme but it does not match the screenshot or the sublime theme.

in fact all the Dark themes seem identical.

**Comment by ajerez** [comment]
Same problem here with VSCode 1.12.1 and SpaceGray Theme 1.2.0

**Comment by pspeter3** [comment]
Yeah, I just noticed this as well.

**Comment by ionutvmi** [comment]
This has been fixed in 1.2.1.

Please let me know if you still have issues.

**Comment by lutzroeder** [comment]
How do we update to 1.2.1? It doesn't show up in VS Code as an update nor are the changes in this Git repo?

**Comment by ionutvmi** [comment]
It should show up in the extensions tab. 

![](http://puu.sh/vV0R2/b6d81d9f1b.png)
